log_level = "debug"

[service]
  [service.Greeter]
    address = "localhost:2080"
    reuse_desc = true
    proto_base_path = "$GOPATH/src/github.com/tgrpc/ngrpc"
    include_imports = "helloworld/helloworld.proto"
    keepalive = "100s"
  [service.LangService]
    address = "localhost:2080"
    reuse_desc = true
    proto_base_path = "$GOPATH/src/github.com/tgrpc/ngrpc"
    include_imports = "helloworld/lang.proto"
    keepalive = "100s"

[[invokes]]
  service = "Greeter"
  method = "helloworld.Greeter/SayHello"
  headers = ["customerId:123", "region:UK"]
  data = "{\"name\":\"tgrpc-tg1\"}"
  n = 2
  interval = "200ms"
  [invokes.resp]
    body = ""
    regexp = ""
    cost = "500ms"
    [invokes.resp.json]
      message = "Hello tgrpc-tg1"

[[invokes]]
  service = "LangService"
  method = "helloworld.LangService/List"
  headers = ["customerId:123", "region:UK"]
  data = "{}"
  n = 2
  interval = "200ms"
  [invokes.resp]
    body = ""
    regexp = ""
    cost = "500ms"
    [invokes.resp.json]
      "langs,0,birthday" = 1136185445.0
      "langs,1,versions,0,id" = 700.0
      "langs,1,versions,0,vf64s" = [111.0, 222.0]
      "langs,1,versions,0,vf64s,0" = 111.0
      "langs,1,versions,0,vi32s" = [111.0, 222.0]
      "langs,1,versions,0,vi32s,0" = 111.0
      "langs,1,versions,0,vi64s" = [111.0, 222.0]
      "langs,1,versions,0,vi64s,0" = 111.0
      "langs,1,versions,0,vstrs" = ["str1", "str2"]
      "langs,1,versions,0,vstrs,0" = "str1"
      totalCount = 999.0
  [invokes.next]
    service = "Greeter"
    method = "helloworld.Greeter/SayHello"
    headers = ["customerId:123", "region:UK"]
    data = "{\"name\":\"tgrpc-tg1\"}"
    n = 2
    interval = "200ms"
    [invokes.next.resp]
      body = ""
      regexp = ""
      cost = "500ms"
      [invokes.next.resp.json]
        message = "Hello tgrpc-tg1"

[[invokes]]
  service = "LangService"
  method = "helloworld.LangService/List"
  headers = ["customerId:123", "region:UK"]
  data = "{}"
  n = 2
  interval = "200ms"
  [invokes.resp]
    body = ""
    regexp = ""
    cost = "500ms"
    [invokes.resp.json]
      "langs,0,birthday" = 1136185445.0
      "langs,1,versions,0,id" = 700.0
      "langs,1,versions,0,vf64s" = [111.0, 222.0]
      "langs,1,versions,0,vf64s,0" = 111.0
      "langs,1,versions,0,vi32s" = [111.0, 222.0]
      "langs,1,versions,0,vi32s,0" = 111.0
      "langs,1,versions,0,vi64s" = [111.0, 222.0]
      "langs,1,versions,0,vi64s,0" = 111.0
      "langs,1,versions,0,vstrs" = ["str1", "str2"]
      "langs,1,versions,0,vstrs,0" = "str1"
      totalCount = 999.0
  [invokes.next]
    service = "Greeter"
    method = "helloworld.Greeter/SayHello"
    headers = ["customerId:123", "region:UK"]
    data = "{\"name\":\"tgrpc-tg1\"}"
    n = 2
    interval = "200ms"
    [invokes.next.resp]
      body = ""
      regexp = ""
      cost = "500ms"
      [invokes.next.resp.json]
        message = "Hello tgrpc-tg1"
